{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-forum-backend.fullname" . }}-nginx-conf
  labels:
    {{- include "django-forum-backend.labels" . | nindent 4 }}
data:
  django.conf.template: |-
    server {
        listen    80;
        listen  [::]:80;
        charset     utf-8;
        client_max_body_size 75M;
        server_name     localhost;
        location /static {
            alias /api/static;
        }
        location /media {
            alias /api/media;
            expires 24h;
        }
        location /flower-internal/ {
            internal;
            rewrite ^/flower-internal/(.*)$ /$1 break;
            proxy_pass ${FLOWER_BACKEND};
            proxy_set_header Host $host;
        }
        location / {
            uwsgi_pass  unix:/api/run/api.sock;        
            include     uwsgi_params;
        }
    }
{{- end }}