{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-forum-backend.fullname" . }}-mysql-conf
  labels:
    {{- include "django-forum-backend.labels" . | nindent 4 }}
data:
  mysql.cnf: |-
    [client]
    default-character-set = utf8mb4
    
    [mysql]
    default-character-set = utf8mb4
     
    [mysqld]
    {{- range .Values.mysql.configMap.mysqld }}
    {{ if .name }}
    {{ .name }} = {{ .value }}
    {{ end }}
    {{- end }}
    default-time-zone='+8:00'
    pid-file = /var/run/mysqld/mysqld.pid
    socket = /var/run/mysqld/mysqld.sock
    datadir = /var/lib/mysql
    log_error = /var/log/mysql/error.log
    character-set-server = utf8mb4
    collation-server = utf8mb4_general_ci
{{- end }}