{{- if .Values.mysql.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-forum-backend.fullname" . }}-mysql
  labels:
    {{- include "django-forum-backend.labels" . | nindent 4 }}
    app: {{ include "django-forum-backend.fullname" . }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "django-forum-backend.selectorLabels" . | nindent 6 }}
      app: {{ include "django-forum-backend.fullname" . }}-mysql
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "django-forum-backend.selectorLabels" . | nindent 8 }}
        app: {{ include "django-forum-backend.fullname" . }}-mysql
    spec:
      terminationGracePeriodSeconds: 20
      {{- with .Values.mysql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django-forum-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-mysql
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.mysql.repository }}:{{ .Values.images.mysql.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.mysql.pullPolicy }}
          env:
          {{- range .Values.mysql.deploy.envs }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-forum-backend.fullname" . }}-mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-forum-backend.fullname" . }}-mysql-secret
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-forum-backend.fullname" . }}-mysql-secret
                  key: mysql-root-password
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 180
            periodSeconds: 60
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-conf
              mountPath: /etc/mysql/conf.d
          resources:
            {{- toYaml .Values.mysql.deploy.resources | nindent 12 }}
      volumes:
      - name: "mysql-conf"
        configMap:
          name: {{ include "django-forum-backend.fullname" . }}-mysql-conf
          items:
            - key: "mysql.cnf"
              path: "mysql.cnf"
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "django-forum-backend.fullname" . }}-mysql-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}