{{- if .Values.phpmyadmin.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-forum-backend.fullname" . }}-phpmyadmin
  labels:
    {{- include "django-forum-backend.labels" . | nindent 4 }}
    app: {{ include "django-forum-backend.fullname" . }}-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "django-forum-backend.selectorLabels" . | nindent 6 }}
      app: {{ include "django-forum-backend.fullname" . }}-phpmyadmin
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "django-forum-backend.selectorLabels" . | nindent 8 }}
        app: {{ include "django-forum-backend.fullname" . }}-phpmyadmin
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django-forum-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-phpmyadmin
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.phpmyadmin.repository }}:{{ .Values.images.phpmyadmin.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.phpmyadmin.pullPolicy }}
          env:
          {{- range .Values.phpmyadmin.deploy.envs }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.phpmyadmin.deploy.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}