{{- if .Values.nginx.enabled -}}
{{- if .Values.nginx.ingress.enabled -}}
{{- $fullName := include "django-forum-backend.fullname" . -}}
{{- $svcPort := .Values.nginx.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "django-forum-backend.fullname" . }}-nginx-ingress
  labels:
    {{- include "django-forum-backend.labels" . | nindent 4 }}
    app: {{ include "django-forum-backend.fullname" . }}-nginx-ingress
  {{- with .Values.nginx.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.nginx.ingress.tls }}
  tls:
    {{- range .Values.nginx.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.nginx.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}-nginx-service
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
