{{- if .Values.phpmyadmin.enabled -}}
{{- if .Values.phpmyadmin.ingress.enabled -}}
{{- $fullName := include "django-forum-backend.fullname" . -}}
{{- $svcPort := .Values.phpmyadmin.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "django-forum-backend.labels" . | nindent 4 }}
    app: {{ include "django-forum-backend.fullname" . }}-phpmyadmin-ingress
  {{- with .Values.phpmyadmin.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.phpmyadmin.ingress.tls }}
  tls:
    {{- range .Values.phpmyadmin.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.phpmyadmin.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}-phpmyadmin-service
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
