{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-forum-backend.fullname" . }}-mysql-secret
  labels:
    {{- include "django-forum-backend.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.secret.mysqlRootPassword | b64enc | quote }}
  mysql-user: {{ .Values.mysql.secret.mysqlUser | b64enc | quote }}
  {{- if .Values.mysql.secret.mysqlPassword }}
  mysql-password: {{ .Values.mysql.secret.mysqlPassword | b64enc | quote }}
  {{- else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}